@echo off
rem Install every app in this release for you alone.
rem Generated by build-bins.py -- do not edit. Options (app names, --list)
rem are handed through to wxl-install.exe.
"%~dp0wxl-install\wxl-install.exe" %*
