@echo off
rem Remove the system-wide install (administrator cmd).
rem Generated by build-bins.py -- do not edit. Options (app names, --list)
rem are handed through to wxl-install.exe.
"%~dp0wxl-install\wxl-install.exe" --system --uninstall %*
