#!/bin/sh
# Install every app in this release for every user:
#     sudo sh install-system.sh
# Generated by make-bins.py -- do not edit. Runs each app's own extract.sh
# (--system); extra options, e.g. --prefix DIR, are handed through.
here="$(cd -- "$(dirname -- "$0")" && pwd)"
failed=""
for app in ccx cpx edx hex searchx trx; do
    echo "== $app =="
    # Every install.sh ends with the same shell-wiring instruction; only the
    # last app prints it, so it is said once, at the end.
    if [ "$app" = trx ]; then q=""; else q=1; fi
    WXL_NO_HINT="$q" sh "$here/$app/extract.sh" --system "$@" \
        || failed="$failed $app"
done
if [ -n "$failed" ]; then
    echo "FAILED:$failed" >&2
    exit 1
fi
