#!/usr/bin/env python3
"""Install every frozen binary shipped in this directory, in one pass.

Generated by make-bins.py -- do not edit; regenerate with a build.

Each app folder here holds an `<app>.tar.gz` and an `extract.sh`, and running
them one at a time is a cd and a command per app. This is the same thing for
all of them at once:

    python3 install-bins.py                   # all of them
    python3 install-bins.py ccx edx           # only those
    python3 install-bins.py --prefix ~/bin    # not the default ~/.local/bin
    python3 install-bins.py --list            # show what would be installed

Stdlib only, and no syntax past Python 3.9: this runs on the *target* machine,
which is the one with no uv, no checkout and nothing installed. The apps
themselves need no Python at all -- each is a statically linked ELF carrying
its own interpreter -- so where there is none, `sh <app>/extract.sh` in each
folder still does exactly what this does.
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Filled in when this file was generated, from the folders that actually came
# out of a build. The zip-only extras (dev-D10) have no extract.sh and are
# therefore not here -- they are unpacked by hand, on Windows.
APPS = ['ccx', 'edx', 'searchx']


def install(app, passthrough):
    """Unpack and install one app through its own extract.sh. True on success.

    `sh extract.sh`, not `./extract.sh`: the exec bit is exactly what the
    transports this tier exists for tend to drop (pylib-D2).
    """
    print("== %s ==" % app)
    sys.stdout.flush()
    # Each install.sh signs off with the same four-line "add this to your
    # ~/.bashrc" instruction. Said once it is the point; said once per app it
    # is noise that buries itself, so the children are silenced and hint()
    # says it at the end, where it is the last thing on screen.
    env = dict(os.environ)
    env["WXL_NO_HINT"] = "1"
    r = subprocess.run(["sh", "extract.sh"] + passthrough,
                       cwd=os.path.join(HERE, app), env=env)
    if r.returncode != 0:
        print("== %s FAILED (exit %d) ==" % (app, r.returncode),
              file=sys.stderr)
        return False
    return True


def hint(apps):
    """Print the shell-wiring instruction once, for the whole run.

    Sourced out of an unpacked app rather than reimplemented here: every
    tarball ships wxlrc.sh, so the text comes from the one place that owns it
    (dev-D11) and cannot drift from what a single-app install prints.
    """
    for app in apps:
        f = os.path.join(HERE, app, app, "wxlrc.sh")
        if os.path.isfile(f):
            subprocess.run(["sh", "-c", '. "$1"; wxl_hint', "sh", f])
            return


def main():
    ap = argparse.ArgumentParser(
        description="install every frozen binary in this directory")
    ap.add_argument("apps", nargs="*", metavar="APP",
                    help="apps to install (default: all of %s)"
                         % ", ".join(APPS))
    ap.add_argument("--prefix", metavar="DIR",
                    help="where the binaries go (default: ~/.local/bin)")
    ap.add_argument("--list", action="store_true",
                    help="show what would be installed, then exit")
    ap.add_argument("-k", "--keep-going", action="store_true",
                    help="carry on after a failure instead of stopping")
    args = ap.parse_args()

    apps = APPS
    if args.apps:
        unknown = [a for a in args.apps if a not in APPS]
        if unknown:
            sys.exit("install-bins.py: not shipped here: %s (have: %s)"
                     % (", ".join(unknown), ", ".join(APPS)))
        apps = args.apps

    if args.list:
        for app in apps:
            print("%s  (%s/%s.tar.gz)" % (app, app, app))
        return 0

    passthrough = ["--prefix", args.prefix] if args.prefix else []
    done, failed = [], []
    for app in apps:
        if install(app, passthrough):
            done.append(app)
        else:
            failed.append(app)
            if not args.keep_going:
                break

    print("")
    if done:
        print("installed: %s" % ", ".join(done))
    sys.stdout.flush()
    if failed:
        print("FAILED: %s" % ", ".join(failed), file=sys.stderr)
        return 1
    hint(done)
    return 0


if __name__ == "__main__":
    sys.exit(main())
