#!/bin/sh
# Remove every app of the local (~/.local) install:
#     sh uninstall.sh
# Generated by make-bins.py -- do not edit. Runs the uninstaller the install
# left beside its manifest, which removes only files it wrote and nobody has
# changed since; settings and state are kept. For an install made with
# --prefix DIR, run DIR/../share/wxl/uninstall.sh instead.
u="${XDG_DATA_HOME:-$HOME/.local/share}/wxl/uninstall.sh"
if [ ! -f "$u" ]; then
    echo "nothing to uninstall: $u not found"
    exit 0
fi
exec sh "$u"
