#!/bin/sh
# Unpack and install cpx from the cpx.tar.gz next to this script.
#
# Generated by pylib/make-bin.sh -- do not edit; regenerate with a build.
#
# Copy both files to the target machine by any means -- scp, a file manager
# over FTP/SFTP, a USB stick, a Windows hop -- and run:
#
#     sh extract.sh
#
# `sh` rather than `./extract.sh` because the exec bit is exactly what those
# transports drop; inside the tarball the modes survive, which is why
# everything else ships in there. Unpacks ./cpx/ beside this script and
# runs its install.sh. Pass --no-install to stop after unpacking; any other
# option (e.g. --prefix DIR) is handed through to install.sh.
set -eu

app="cpx"
tarball="$app.tar.gz"
here="$(cd -- "$(dirname -- "$0")" && pwd)"

case "${1:-}" in
    -h|--help)
        cat >&2 <<USAGE
usage: sh extract.sh [--no-install] [install.sh options...]

  unpacks $here/$app/ from $tarball and runs its install.sh
  --no-install   unpack only, then print the install command
USAGE
        exit 0
        ;;
esac

do_install=yes
if [ "${1:-}" = "--no-install" ]; then
    do_install=no
    shift
fi

if [ ! -f "$here/$tarball" ]; then
    echo "extract.sh: $here/$tarball not found -- copy it over as well," \
         "this script is only the opener" >&2
    exit 1
fi

tar -xzf "$here/$tarball" -C "$here"
echo "unpacked $here/$app/"

if [ "$do_install" = no ]; then
    echo "to install: sh $here/$app/install.sh"
    exit 0
fi

# `sh`, not the exec bit: the archive preserved it, but this stays true even
# if the directory was unpacked by some other tool that did not.
exec sh "$here/$app/install.sh" "$@"
